### ISSUE TITLE
Simplify nur für einzelne Archive möglich

### ISSUE THREAD

**Issue by fhreg** [kozi/contao-simplify#3]
Hallo, ich verwende Simplify mit Contao 3.5.3 und habe eine Weile gebraucht um herauszufinden, dass man es in den Settings aktivieren muss. In den Screenshots hier bei Github ist aber zu sehen, dass dies auch für ein einzelnes Archiv möglich ist und nicht global für alle News. Wie kann ich das soweit umstellen. Beim Bearbeiten des Archives habe ich die Simplify-Einstellungen gar nicht.

**Comment by kozi** [comment]
Welche Version ist denn installiert? In der akuellen Version 0.8.3 https://github.com/kozi/contao-simplify/releases/tag/0.8.3 sollte es KEINE Einstellungsmöglichkeiten in den "Settings" geben. Die Funktion wird nur noch über die Einstellungen im Nachrichtenarchiv aktiviert.

**Comment by xegni44** [comment]
Ich greife das nochmal auf...
ich hätte auch gerne die Möglichkeit der Einstellung in einzelnen Archiven.
Gibt es ein Update dafür ohne Composer? 
Danke schonmal für eine Antwort.
